# The language is set to python to ensure virtualenv and python exist for the
# tests.
language: python

sudo: required
services:
  - docker

env:
  matrix:
    - BASE_DISTRO=centos-7
    - BASE_DISTRO=debian-9
    - BASE_DISTRO=debian-10
    - BASE_DISTRO=fedora-28
    - BASE_DISTRO=fedora-29
    - BASE_DISTRO=fedora-30
    - BASE_DISTRO=opensuse-15.0
    - BASE_DISTRO=opensuse-15.1
    - BASE_DISTRO=ubuntu-16.04
    - BASE_DISTRO=ubuntu-18.04

  global:
    - REPO=crops/poky
    - DEFAULT_DISTRO=ubuntu-18.04
    - secure: "mMM/4HvQOxTQldvbJkHZBOjyfxF8MQt4C3xmYMXU3L5HJ0OItk0jrGR6rqb04sndHaoCNKuBkq2FXcSaEIndDoaDXQ3+4rhFzAu4rXspdgAj0E0tG6dAqgAu7woQvgouwkEsD0G7XBada+TIJHG777pFD/5mrcL3taKLh5BSr2kgDQKYMEo0+GSrL69onbP7XIuwpk4Kyr3UChDl/Mbqu23Xq4LoEW5tmwHiYHi2PLQ0mw/FXoj1U+BmAxuuooNZEVCR9dcO5SnSqCQXlEEG2nuKBjZSulMGGTG8Rsovz3j4TVdDhig8++3VqQd/TA8s4CQeB8A5Gd/4Ao4Zl61R96qP7PMLfRHBfZmnfubH0OUJgIORqSU7Z9BoxgnUUyK/p5wq56pgbOAd3J4DY4Tl+bm6Lry18lyv1SC4ZOrqBWv6LmGQVZSF2qytNg9l2vBJ9E9VMHC9yZqFd8LfdWv77tjYGY+NgfEqgza289imjr1UWyXsz6dpGiS6G4bTmdgdxSm3IUglYl7I1HF/LaibopfJsAttyii1eOogrKN5nCkK0ks3mB858tD4Rll7QItpM1LbXNxQL9TD6Q2M5TUZyQiwy1hY9r0m96sm2MjoCt8oe1xM3TcTdO5V1r5rQSrwp3mxO+lZE/u30cVDG3f+jrZ7XflY1OptHYt4Y0hEGkI="
    - secure: "dhrF2KV21RiLLg5MxBVau5mDdHPQDqH8lljldjXjQprjqQabiw9/SyYQ5CWXZAbwT2KIrScZQ/7SiblQke2eLxKf3oEuGLERsDRHyb2Nm6D7g47oqNuHo+jDMmc2K+QboTnpmkq1Txy43mpMyBWAkNWcQ6/gU5jyAhCnsXXtX804ayNutaAoS+625ius/xje/aVIcpjL0cIx8QT8cczkwFW5VDLb/canq7sXZCXdej+rN+NV+zVBvuaEcKCUH6Ev5V3vszcaF4gfJWmNRgal0wETtukYNRh+r6nMoSkSFSYRX/AFHGTg6puf0qzvj1Gc5BggA3L/0z1IORK1MfB43HaP5XibVDgnpS/Agr0LcnpNWfpEDyhGY9+CNyG7QDBebF/c3N74Dt4W4IBWAdSPYhwVJ61WPwUPiNrA0r10aaJpkEl3KlOe2FYcqWSKPiSTym6bO74s/AMmczZYklYtPhOuL2AETIlaHYfskMMmBJuMeGfVV3LqatvjIALA5e5aB7AIdzMHsqUofTjQ1KJXOuJjMAUp9Arve1TgiPeL5dPfUfFnjMU2Rm3TwIhOBkQShznGQiZ1dYnmtI11NG6yRNNu8FRwbVcy4bOQG+28F+Cu9vHYjWrCK3A+zIuVn3k/YUMIQJX/fjMZ4JbsCx1vcsesTMU6Ts0fJbCssAgq8Z8="

before_install:
  # For annotate-output
  - sudo apt-get install -y devscripts

script:
  - ./build-and-test.sh

after_success:
  - bash deploy.sh

notifications:
  email:
    recipients:
      - brian.avery@intel.com
      - randy.e.witt@intel.com
    on_success: change
    on_failure: always
