# The language is set to python to ensure virtualenv and python exist for the
# tests.
language: python

sudo: required
services:
  - docker

env:
  matrix:
    - BASE_DISTRO=centos-7
    - BASE_DISTRO=debian-8
    - BASE_DISTRO=fedora-22
    - BASE_DISTRO=fedora-23
    - BASE_DISTRO=fedora-24
    - BASE_DISTRO=fedora-25
    - BASE_DISTRO=opensuse-13.2
    - BASE_DISTRO=opensuse-42.1
    - BASE_DISTRO=opensuse-42.2
    - BASE_DISTRO=ubuntu-14.04
    - BASE_DISTRO=ubuntu-16.04
    - BASE_DISTRO=ubuntu-16.10

  global:
    - REPO=crops/poky
    - DEFAULT_DISTRO=ubuntu-14.04
    - secure: "Elbh4m0BAIUiYaF5dukzGPppQVipTKI3ZshUWhOgGYzmLC/OBw9MzHD/rSiil+cJk2LhDvqQNvtWVbrVIVOCf/uM9G5j2lvIuATiVgndQG7ne/xTIpFr3PRVXfL4tCXJOP10HCGceHjY78uK2aZuqwolIMM4ITx8hvWwIzE9fx6RBwVxPCVWm3FN5r4M3PNCkin6s+PGFSUNSXBEBNytHuhULODdGhMD5KUMC0M5kUz2NCGHICBrKdqq/uNOLVhkayVE1LgOBWHx9oDDX20romJS7tuaKc2CWS3Qaxf7lJMgCCzGqHdF+hhK7DR4fZefKtuyW+InEiB4FrKfPFM43iz72P9moRaoZZJ3w5LZjHBinKiB5m8Nfe3MHfxF1s25+6ToRkgnGi+0swEM2gkifdmW78urFz8TqQ8eQ9jHa5xjVBC/splVqKqlAhOmHiqNc0pffCs/poyCge9IEAKu4Sm+EpknAWPsawnph3Q0UW1n8x8E7XXWdAzAD4CCGdxCe1fyrw3RcywqWMlNm5/7QjBeeNdYzS7BOcyj8l31B0KMADFI6scpMhMTY7n56/7bJovCFq2zqpos/YmaufHSj07CvUNL/u2e9wNbrxiDKh5EFgaPqvZYt/uEtSTdvAk7uShvVzhf4sk+GzR3AWdja4IZMNCqzJ9yxFk7MZRfO6E="
    - secure: "n/0cc9tfQ8U86bTL4wdKhlqgk3DEeD9z7a6ViyDMEztsuNwX8+ziCusnO1LPFpiEe9ktO6gJPf9c9ejr6sWIT4xs05Xtgym0mnz0VqS71l8L/xUnWDcMVzyKpZsGfAOadYKcz9JIiPV63ssJGxlUpGB/NICgLGuj9aYuBzS5Ob7eILtFwVkGqK6lZ038fYaO+1Tphc53QWipY/z60XbB+0zR9NHts6dYlpHyknfPoigUHC9nWgafZnLVO7C4+pFrotHzAXfMqj3ZRyTRTgqxMX91j2Xnsi6V+qIk/oAJWF/ODTQKaJDekgjrUd6nn/WxImMTXoSaVaUtzXq/s50ebvK1iD7IDpvCZRux6D2mdwKFFwQxMcac0NcbG9M5vs9Q5MoSuNieNr8DaDDgICOCRVmnm5BW2+RGtfY0UpQtKXy5ST0QwMmHV9vX/qBd9haK0JjzJkBJPOLNkvSdIJMT7la+jTuX2K8DQhlPVxhWMBJ43oXA38OGq3lD+Y/zGYVyA3usm16eaUtgoPjk9gDs5f1NB65zTK87fpink902kov3WHrRQ8fJ1ikU6PUjC2iBxjxI4KOSmRALmLuXJ/NQnXjqhnztGahuvnI3E945BCB9cmnyyibYFRM5LjDAzD78Ii2qo1oWzvlRNk4PwgR9810BFI6vuHb5jo/3FG9Fcuw="

before_install:
  # For annotate-output
  - sudo apt-get install -y devscripts

script:
  - sed -i -e "s#FROM crops/yocto:ubuntu-14.04#FROM crops/yocto:${BASE_DISTRO}#" Dockerfile
  - docker build -t ${REPO}:${BASE_DISTRO} .
  - annotate-output bash -c "cd tests; ./runtests.sh ${REPO}:${BASE_DISTRO}"

after_success:
  - bash deploy.sh

notifications:
  email:
    recipients:
      - brian.avery@intel.com
      - randy.e.witt@intel.com
    on_success: change
    on_failure: always
